<?xml version="1.0"?>
<wsdl:definitions targetNamespace="http://api.dpdirect.org/Namespace/STS/ServicesProxy/Interface/V1"
	xmlns:tns="http://api.dpdirect.org/Namespace/STS/ServicesProxy/Interface/V1" xmlns:wst="http://docs.oasis-open.org/ws-sx/ws-trust/200512/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
	xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy"
	xmlns:otps-wst="http://www.rsasecurity.com/rsalabs/otps/schemas/2005/09/otps-wst#">
	<wsp:Policy wsu:Id="RequestPolicy">
		<wsp:PolicyReference URI="#UserPasswordOtpPolicy"/>
		<wsp:PolicyReference URI="#RequestAddressingPolicy"/>
	</wsp:Policy>
	<wsp:Policy wsu:Id="ValidateRequestPolicy">
		<wsp:PolicyReference URI="#RequestAddressingPolicy"/>
	</wsp:Policy>
	<wsp:Policy wsu:Id="ResponsePolicy">
		<wsp:PolicyReference URI="#ResponseAddressingPolicy"/>
	</wsp:Policy>
	<wsp:Policy wsu:Id="UserPasswordOtpPolicy">
		<wsp:All>
			<sp:UsernameToken
				sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient"/> 
			<otps-wst:OtpToken
				sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient"/> 
		</wsp:All>
	</wsp:Policy>
	<wsp:Policy wsu:Id="RequestAddressingPolicy">
		<wsp:All>
			<sp:RequiredElements>
				<!-- wsa:MessageID -->
				<sp:XPath>/*[local-name() = 'Envelope']/*[local-name() = 'Header']/*[local-name() = 'MessageID' and
					namespace-uri() = 'http://www.w3.org/2005/08/addressing'][1]</sp:XPath>
			</sp:RequiredElements>
			<sp:RequiredElements>
				<!-- wsa:Action -->
				<sp:XPath>/*[local-name() = 'Envelope']/*[local-name() = 'Header']/*[local-name() = 'Action' and
					namespace-uri() = 'http://www.w3.org/2005/08/addressing'][1]</sp:XPath>
			</sp:RequiredElements>
		</wsp:All>
	</wsp:Policy>
	<wsp:Policy wsu:Id="ResponseAddressingPolicy">
		<wsp:All>
			<sp:RequiredElements>
				<!-- wsa:MessageID -->
				<sp:XPath>/*[local-name() = 'Envelope']/*[local-name() = 'Header']/*[local-name() = 'MessageID' and
					namespace-uri() = 'http://www.w3.org/2005/08/addressing'][1]</sp:XPath>
			</sp:RequiredElements>
			<sp:RequiredElements>
				<!-- wsa:Action -->
				<sp:XPath>/*[local-name() = 'Envelope']/*[local-name() = 'Header']/*[local-name() = 'Action' and
					namespace-uri() = 'http://www.w3.org/2005/08/addressing'][1]</sp:XPath>
			</sp:RequiredElements>
			<sp:RequiredElements>
				<!-- wsa:RelatesTo -->
				<sp:XPath>/*[local-name() = 'Envelope']/*[local-name() = 'Header']/*[local-name() = 'RelatesTo' and
					namespace-uri() = 'http://www.w3.org/2005/08/addressing'][1]</sp:XPath>
			</sp:RequiredElements>
		</wsp:All>
	</wsp:Policy>
	<!-- =================== Type Definitions ==================================== -->
	<wsdl:types>
		<xs:schema targetNamespace="http://api.dpdirect.org/Namespace/STS/ServicesProxy/Interface/V1">
			<xs:import namespace="http://docs.oasis-open.org/ws-sx/ws-trust/200512/"
				schemaLocation="../../XSD/ws-trust-1.3.xsd"/>
			<xs:import namespace="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy"
				schemaLocation="../../XSD/ws-policy200507.xsd"/>
		</xs:schema>
	</wsdl:types>
	<!-- =================== Message Definitions  =============================== -->
	<!-- WS-Trust defines the following GEDs -->
	<wsdl:message name="RequestSecurityTokenMsg">
		<wsdl:part name="request" element="wst:RequestSecurityToken"/>
	</wsdl:message>
	<wsdl:message name="RequestSecurityTokenResponseMsg">
		<wsdl:part name="response" element="wst:RequestSecurityTokenResponse"/>
	</wsdl:message>
	<wsdl:message name="RequestSecurityTokenResponseCollectionMsg">
		<wsdl:part name="responseCollection" element="wst:RequestSecurityTokenResponseCollection"/>
	</wsdl:message>
	<!-- STS Error -->
	<wsdl:message name="Error">
		<wsdl:part name="Error" type="xs:string"/>
	</wsdl:message>
	<!-- =================== PortType Definitions  ================================ -->
	<wsdl:portType name="WSSecurityRequestor">
		<wsdl:operation name="SecurityTokenResponse">
			<wsdl:input message="tns:RequestSecurityTokenResponseMsg"/>
		</wsdl:operation>
		<wsdl:operation name="SecurityTokenResponse2">
			<wsdl:input message="tns:RequestSecurityTokenResponseCollectionMsg"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:portType name="SecurityTokenRequestService">
		<wsdl:operation name="RequestSecurityToken">
			<wsdl:input name="RequestSecurityTokenMsg" message="tns:RequestSecurityTokenMsg"/>
		</wsdl:operation>
	</wsdl:portType>
	<!-- This portType models the full request/response the Security Token  Service: -->
	<wsdl:portType name="SecurityTokenService">
		<wsdl:operation name="RequestSecurityTokenIssue">
			<wsdl:input name="RequestSecurityTokenIssueMsg" message="tns:RequestSecurityTokenMsg"/>
			<wsdl:output name="RequestSecurityTokenResponseCollectionMsg" message="tns:RequestSecurityTokenResponseCollectionMsg"/>
		</wsdl:operation>
		<wsdl:operation name="RequestSecurityTokenValidate">
			<wsdl:input name="RequestSecurityTokenValidateMsg" message="tns:RequestSecurityTokenMsg"/>
			<wsdl:output name="RequestSecurityTokenResponseMsg" message="tns:RequestSecurityTokenResponseMsg"/>
		</wsdl:operation>
	</wsdl:portType>
	<!-- =================== Binding Definitions ================================= -->
	<wsdl:binding name="SecureTokenService_SOAP_Binding" type="tns:SecurityTokenService">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="RequestSecurityTokenIssue">
			<soap:operation style="document" soapAction="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Issue"/>
			<wsdl:input name="RequestSecurityTokenIssueMsg">
				<soap:body use="literal"/>
				<wsp:PolicyReference URI="#RequestPolicy"/>
			</wsdl:input>
			<wsdl:output name="RequestSecurityTokenResponseCollectionMsg">
				<soap:body use="literal"/>
				<!--<wsp:PolicyReference URI="#ResponsePolicy"/>-->
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="RequestSecurityTokenValidate">
			<soap:operation style="document" soapAction="http://docs.oasis-open.org/ws-sx/ws-trust/200512/RST/Validate"/>
			<wsdl:input name="RequestSecurityTokenValidateMsg">
				<soap:body use="literal"/>
				<wsp:PolicyReference URI="#ValidateRequestPolicy"/>
			</wsdl:input>
			<wsdl:output name="RequestSecurityTokenResponseMsg">
				<soap:body use="literal"/>
				<!--<wsp:PolicyReference URI="#ResponsePolicy"/>-->
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<!-- =================== Service Definitions ================================== -->
	<wsdl:service name="SecureTokenService">
		<!-- HTTP Binding -->
		<wsdl:port name="SecureTokenService_SOAP_Port_HTTP" binding="tns:SecureTokenService_SOAP_Binding">
			<soap:address location="http://localhost/STS"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
