<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:tns="http://www.dpdirect.org/Namespace/Verify/ServicesProxy/Interface/V1"
	xmlns:verify="http://www.dpdirect.org/Namespace/Verify/Services/V1.0"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:wsa="http://www.w3.org/2005/08/addressing"
	xmlns:wst="http://docs.oasis-open.org/ws-sx/ws-trust/200512"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
	xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	name="Verify_ServicesProxy_Interface_V1"
	targetNamespace="http://www.dpdirect.org/Namespace/Verify/ServicesProxy/Interface/V1">
	<!-- =================== WS-Policy Definitions =============================== -->
	<wsp:Policy wsu:Id="RequestPolicy">
		<wsp:PolicyReference URI="#MutualSecurityPolicy"/>
		<wsp:PolicyReference URI="#RequestAddressingPolicy"/>
	</wsp:Policy>
	<wsp:Policy wsu:Id="ResponsePolicy">
		<wsp:PolicyReference URI="#MutualSecurityPolicy"/>
		<wsp:PolicyReference URI="#ResponseAddressingPolicy"/>
	</wsp:Policy>
	<wsp:Policy wsu:Id="MutualSecurityPolicy">
		<wsp:All>
			<!-- Mandatory inclusion WS-Security Timestamp -->
			<sp:IncludeTimestamp/>
			<sp:RequiredElements>
				<!-- wsu:Timestamp -->
				<sp:XPath>/*[local-name() = 'Envelope']/*[local-name() = 'Header']/*[local-name() = 'Security' and
					namespace-uri() =
					'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd']/*[local-name()
					= 'Timestamp' and namespace-uri()
					='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd']</sp:XPath>
			</sp:RequiredElements>
			<!-- Issued SAML Token -->
			<sp:IssuedToken>
				<sp:Issuer>
					<wsa:EndpointReference>
						<wsa:Address>https://api.dpdirect.org/authenticate</wsa:Address>
					</wsa:EndpointReference>
				</sp:Issuer>
				<sp:RequestSecurityTokenTemplate>
					<wst:TokenType>
						http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.1#SAMLV2.0
					</wst:TokenType>
				</sp:RequestSecurityTokenTemplate>
			</sp:IssuedToken>
		</wsp:All>
	</wsp:Policy>
	<wsp:Policy wsu:Id="RequestAddressingPolicy">
		<wsp:All>
			<sp:RequiredElements>
				<!-- wsa:MessageID -->
				<sp:XPath>/*[local-name() = 'Envelope']/*[local-name() = 'Header']/*[local-name() = 'MessageID' and
					namespace-uri() = 'http://www.w3.org/2005/08/addressing'][1]</sp:XPath>
			</sp:RequiredElements>
			<sp:RequiredElements>
				<!-- wsa:Action -->
				<sp:XPath>/*[local-name() = 'Envelope']/*[local-name() = 'Header']/*[local-name() = 'Action' and
					namespace-uri() = 'http://www.w3.org/2005/08/addressing'][1]</sp:XPath>
			</sp:RequiredElements>
		</wsp:All>
	</wsp:Policy>
	<wsp:Policy wsu:Id="ResponseAddressingPolicy">
		<wsp:All>
			<sp:RequiredElements>
				<!-- wsa:MessageID -->
				<sp:XPath>/*[local-name() = 'Envelope']/*[local-name() = 'Header']/*[local-name() = 'MessageID' and
					namespace-uri() = 'http://www.w3.org/2005/08/addressing'][1]</sp:XPath>
			</sp:RequiredElements>
			<sp:RequiredElements>
				<!-- wsa:Action -->
				<sp:XPath>/*[local-name() = 'Envelope']/*[local-name() = 'Header']/*[local-name() = 'Action' and
					namespace-uri() = 'http://www.w3.org/2005/08/addressing'][1]</sp:XPath>
			</sp:RequiredElements>
			<sp:RequiredElements>
				<!-- wsa:RelatesTo -->
				<sp:XPath>/*[local-name() = 'Envelope']/*[local-name() = 'Header']/*[local-name() = 'RelatesTo' and
					namespace-uri() = 'http://www.w3.org/2005/08/addressing'][1]</sp:XPath>
			</sp:RequiredElements>
		</wsp:All>
	</wsp:Policy>
	<!-- =================== Type Definitions ==================================== -->
	<wsdl:types>
		<xs:schema targetNamespace="http://www.dpdirect.org/Namespace/Verify/ServicesProxy/Interface/V1">
			<xs:import namespace="http://www.dpdirect.org/Namespace/Verify/Services/V1.0"
				schemaLocation="../../XSD/VerifyRequest.xsd"/>
			<xs:import namespace="http://www.dpdirect.org/Namespace/Verify/Services/V1.0"
				schemaLocation="../../XSD/VerifyResponse.xsd"/>
		</xs:schema>
	</wsdl:types>
	<!-- =================== Message Definitions  =============================== -->
	<wsdl:message name="VerifyRequest">
		<wsdl:part element="verify:VerifyRequest" name="request"/>
	</wsdl:message>
	<wsdl:message name="VerifyResponse">
		<wsdl:part element="verify:VerifyResponse" name="response"/>
	</wsdl:message>

	<!-- =================== PortType Definitions  ================================ -->
	<wsdl:portType name="Verify_ServicesProxy_PortType_V1">
		<wsdl:operation name="Verify">
			<wsdl:input name="VerifyRequest" message="tns:VerifyRequest"/>
			<wsdl:output name="VerifyResponse" message="tns:VerifyResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<!-- =================== Binding Definitions ================================= -->
	<wsdl:binding name="Verify_ServicesProxy_SOAP11_Binding_V1" type="tns:Verify_ServicesProxy_PortType_V1">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="Verify">
			<soap:operation style="document"
				soapAction="http://www.dpdirect.org/Namespace/Verify/ServicesProxy/Interface/V1/Verify_ServicesProxy_PortType_V1/Verify"/>
			<wsdl:input name="VerifyRequest">
				<soap:body use="literal"/>
				<wsp:PolicyReference URI="#RequestPolicy"/>
			</wsdl:input>
			<wsdl:output name="VerifyResponse">
				<soap:body use="literal"/>
				<wsp:PolicyReference URI="#ResponsePolicy"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<!-- =================== Service Definitions ================================== -->
	<wsdl:service name="Verify_ServicesProxy_Service_V1">
		<!-- HTTP Binding -->
		<wsdl:port name="Verify_ServicesProxy_SOAP11_Port_HTTP"
			binding="tns:Verify_ServicesProxy_SOAP11_Binding_V1">
			<soap:address location="http://localhost/Verify"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
